//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public int LoanID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AuditName { get; set; }
        public System.DateTime AuditDate { get; set; }
        public Nullable<int> NewStatusID { get; set; }
    }
}
